import{readFile,writeFile}from'node:fs/promises';
const rows=JSON.parse(await readFile('results.json','utf8')),cases=JSON.parse(await readFile('cases.json','utf8'));if(rows.length!==216)throw Error('Benchmark is not complete: '+rows.length);
const median=values=>{const a=[...values].sort((x,y)=>x-y);return a.length%2?a[(a.length-1)/2]:(a[a.length/2-1]+a[a.length/2])/2;};const percentile=(v,p)=>[...v].sort((a,b)=>a-b)[Math.ceil(v.length*p)-1];
function semantic(r,c){if(!r.choices)return false;return Object.entries(c.gold).every(([id,gold])=>{const chosen=r.choices[id];if(chosen===gold)return true;const desc=c.questions[id].criteria[gold];return typeof desc==='string'&&chosen===desc;});}
const summaries={};for(const task of [...new Set(rows.map(r=>r.task))]){const tt=rows.filter(r=>r.task===task);const s={providers:{}};for(const provider of ['jev','qwen']){const r=tt.filter(r=>r.provider===provider);const good=r.filter(r=>r.correct);s.providers[provider]={n:r.length,exactCorrect:r.filter(r=>r.correct).length,semanticCorrect:r.filter(r=>semantic(r,cases.find(c=>c.id===r.id))).length,correctLabels:r.reduce((n,r)=>n+r.labelCorrect,0),labels:r.reduce((n,r)=>n+r.labelCount,0),invalidFormatOrChoice:r.filter(r=>!r.valid).length,httpErrors:r.filter(r=>r.httpStatus||r.error==='timeout'||r.error==='request_failed').length,medianMs:median(r.map(r=>r.elapsedMs)),p95Ms:percentile(r.map(r=>r.elapsedMs),.95),correctOnlyMedianMs:good.length?median(good.map(r=>r.elapsedMs)):null,inputTokens:r.reduce((s,r)=>s+(r.usage?.input_tokens||r.usage?.prompt_tokens||0),0),outputTokens:r.reduce((s,r)=>s+(provider==='qwen'?r.usage?.completion_tokens||0:0),0)};}
const paired=[];for(const c of cases.filter(c=>c.task===task))for(let round=1;round<=3;round++){const j=tt.find(r=>r.id===c.id&&r.round===round&&r.provider==='jev'),q=tt.find(r=>r.id===c.id&&r.round===round&&r.provider==='qwen');paired.push({id:c.id,round,jevMs:j.elapsedMs,qwenMs:q.elapsedMs,deltaMs:q.elapsedMs-j.elapsedMs,ratio:q.elapsedMs/j.elapsedMs,bothCorrect:j.correct&&q.correct,jevCorrect:j.correct,qwenCorrect:q.correct});}
s.medianRatio=s.providers.qwen.medianMs/s.providers.jev.medianMs;s.pairedMedianRatio=median(paired.map(p=>p.ratio));s.jevFasterTrials=paired.filter(p=>p.jevMs<p.qwenMs).length;s.bothCorrectPairs=paired.filter(p=>p.bothCorrect).length;const both=paired.filter(p=>p.bothCorrect);s.bothCorrectMedians=both.length?{jevMs:median(both.map(p=>p.jevMs)),qwenMs:median(both.map(p=>p.qwenMs))}:null;
s.rounds=[1,2,3].map(round=>({round,...Object.fromEntries(['jev','qwen'].map(provider=>{const r=tt.filter(r=>r.provider===provider&&r.round===round);return[provider,{medianMs:median(r.map(r=>r.elapsedMs)),correct:r.filter(r=>r.correct).length,n:r.length}]}))}));
let seed=885;const rand=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};const clusters=cases.filter(c=>c.task===task).map(c=>paired.filter(p=>p.id===c.id));const ratios=[];for(let b=0;b<10000;b++){const sample=[];for(let i=0;i<clusters.length;i++)sample.push(...clusters[Math.floor(rand()*clusters.length)]);ratios.push(median(sample.map(p=>p.qwenMs))/median(sample.map(p=>p.jevMs)));}ratios.sort((a,b)=>a-b);s.caseClusterBootstrapRatio95CI=[ratios[250],ratios[9750]];s.pairs=paired;summaries[task]=s;}
await writeFile('summary.json',JSON.stringify(summaries,null,2)+'\n');console.log(JSON.stringify(Object.fromEntries(Object.entries(summaries).map(([task,s])=>[task,{providers:s.providers,medianRatio:s.medianRatio,jevFasterTrials:s.jevFasterTrials,bothCorrectPairs:s.bothCorrectPairs,bothCorrectMedians:s.bothCorrectMedians,caseClusterBootstrapRatio95CI:s.caseClusterBootstrapRatio95CI,rounds:s.rounds}])),null,2));
