import{writeFile}from'node:fs/promises';import{createHash}from'node:crypto';
const memory=[
{id:'repeat',english:'Could you repeat that?',dutch:'Kunt u dat herhalen?'},
{id:'slower',english:'Could you speak more slowly?',dutch:'Kunt u langzamer spreken?'},
{id:'card',english:'Can I pay by debit card?',dutch:'Kan ik pinnen?'},
{id:'station',english:'Where is the train station?',dutch:'Waar is het treinstation?'},
{id:'receipt',english:'May I have the receipt?',dutch:'Mag ik de bon?'},
{id:'reservation',english:'I have a reservation.',dutch:'Ik heb een reservering.'},
{id:'help',english:'Could you help me?',dutch:'Kunt u me helpen?'},
{id:'understand',english:'I do not understand.',dutch:'Ik begrijp het niet.'}
];
const cases=[];
function add(id,category,source,context,gold,extras={}){cases.push({id,category,material:{source,context,sourceLanguage:'English',targetLanguage:'Dutch',senseOptions:{},memory:[],...extras},gold});}
const cacheSources=[['repeat','Would you mind saying that again?'],['slower','Would you mind talking a bit more slowly?'],['card','Is it possible to pay with my debit card?'],['station','Where can I find the railway station?'],['receipt','Could I have the receipt, please?'],['reservation','There is a reservation in my name.'],['help','Would you be able to help me?'],['understand',"I don't understand."]];
for(const [index,[id,source]]of cacheSources.entries())add('m'+(index+1),'memory',source,'Polite service conversation with one unfamiliar adult. A debit-card question, if present, concerns a debit card, not credit.',{action:'translate',memory:id,reference:memory.find(m=>m.id===id).dutch,requirements:['Preserve the request or statement; polite u is appropriate when addressing the listener.']},{memory});
add('s1','sense',"I'll wait by the bank.",'Two kayakers discuss where to meet along a river. There is no financial business involved.',{action:'translate',sense:'river',reference:'Ik wacht bij de oever.',requirements:['bank must mean riverbank/oever, not financial bank.']},{senseOptions:{river:'river edge; Dutch oever',financial:'financial institution; Dutch bank',bench:'seat; Dutch bankje'}});
add('s2','sense','Check the charge before we leave.','An engineer is talking about a rechargeable battery, not an invoice or accusation.',{action:'translate',sense:'electrical',reference:'Controleer de lading voordat we vertrekken.',requirements:['charge refers to battery charge/lading.']},{senseOptions:{electrical:'stored electrical charge; lading',fee:'money owed; kosten',accusation:'legal allegation; aanklacht'}});
add('s3','sense','Has the interest changed?','The customer asks a bank about the annual percentage paid on a savings account.',{action:'translate',sense:'rate',reference:'Is de rente veranderd?',requirements:['interest must be rente, not belangstelling.']},{senseOptions:{rate:'financial interest rate; rente',curiosity:'attention or curiosity; belangstelling',stake:'ownership or stake; belang'}});
add('s4','sense','Keep the bat inside until sunset.','A wildlife carer is rehabilitating an injured flying mammal.',{action:'translate',sense:'animal',reference:'Houd de vleermuis tot zonsondergang binnen.',requirements:['bat is vleermuis, not a sports implement.']},{senseOptions:{animal:'flying mammal; vleermuis',sport:'sports bat; knuppel'}});
add('s5','sense','The spring needs replacing.','A mechanic is repairing the coiled metal component in a door closer.',{action:'translate',sense:'coil',reference:'De veer moet worden vervangen.',requirements:['spring is mechanical veer, not season or water source.']},{senseOptions:{coil:'elastic mechanical coil; veer',season:'season after winter; lente',water:'natural water source; bron'}});
add('s6','sense','The seal is damaged.','A plumber is inspecting the rubber ring that prevents a tap from leaking.',{action:'translate',sense:'gasket',reference:'De afdichting is beschadigd.',requirements:['seal is afdichting, not animal or official stamp.']},{senseOptions:{gasket:'leak-preventing seal; afdichting',animal:'marine mammal; zeehond',stamp:'official stamp; zegel'}});
add('s7','sense','This port is blocked.','The IT team is inspecting firewall rules for network connections.',{action:'translate',sense:'network',reference:'Deze poort is geblokkeerd.',requirements:['port is network poort, not harbor or wine.']},{senseOptions:{network:'network communication port; poort',harbor:'place for ships; haven',wine:'fortified wine; port'}});
add('s8','sense','Please prepare the minutes by Friday.','A secretary is asked to write the record of a committee meeting.',{action:'translate',sense:'record',reference:'Stel de notulen alstublieft uiterlijk vrijdag op.',requirements:['minutes are meeting notulen; by Friday is a deadline.']},{senseOptions:{record:'written record of a meeting; notulen',time:'units of time; minuten'}});
add('r1','register','Can you send me your address?','A business representative politely addresses one unfamiliar adult customer. Use formal singular Dutch.',{action:'translate',register:'formal',reference:'Kunt u mij uw adres sturen?',requirements:['Use u/uw, not jij/je or jullie.']});
add('r2','register','Can you send me your address?','A teenager speaks casually to one close friend. Use informal singular Dutch.',{action:'translate',register:'informal',reference:'Kun je me je adres sturen?',requirements:['Use je/jij and je/jouw; do not use formal u.']});
add('r3','register','Have you brought your tickets?','A teacher addresses a group of students, not a single person.',{action:'translate',register:'plural',reference:'Hebben jullie jullie kaartjes meegenomen?',requirements:['Address the group with jullie; preserve plural tickets.']});
add('r4','register','Would you like to take a seat?','A receptionist speaks courteously to an unfamiliar older customer. Formal singular Dutch is required.',{action:'translate',register:'formal',reference:'Wilt u plaatsnemen?',requirements:['Use formal u, not informal je.']});
add('n1','meaning','Only cancel the second booking, not both.','There are exactly two bookings. The first booking must remain active.',{action:'translate',reference:'Annuleer alleen de tweede boeking, niet allebei.',requirements:['Cancel second only; preserve first.']});
add('n2','meaning','Do not delay canceling the 14:30 booking.','The speaker wants the cancellation to happen immediately, not to postpone it.',{action:'translate',reference:'Stel het annuleren van de boeking van 14:30 niet uit.',requirements:['Cancel without delay; do not invert into do not cancel. Preserve 14:30.']});
add('n3','meaning','Anna owes Bram 125 euros, not the other way around.','The named people and the amount must be preserved exactly.',{action:'translate',reference:'Anna is Bram 125 euro schuldig, niet andersom.',requirements:['Anna is debtor; Bram creditor; amount 125 euros.']});
add('n4','meaning','Move the appointment from Tuesday to Thursday, not from Thursday to Tuesday.','The appointment is currently scheduled for Tuesday.',{action:'translate',reference:'Verplaats de afspraak van dinsdag naar donderdag, niet andersom.',requirements:['New day Thursday; original day Tuesday.']});
add('n5','meaning','I did not say that Eva stole the keys.','Do not add a claim that Eva is innocent or that someone else stole them; preserve only the stated denial of saying this.',{action:'translate',reference:'Ik heb niet gezegd dat Eva de sleutels heeft gestolen.',requirements:['Negation applies to saying; do not turn it into Eva did not steal.']});
add('n6','meaning','If the payment has not arrived by Monday, do not ship the order.','The condition must be retained; this is not an unconditional instruction never to ship.',{action:'translate',reference:'Als de betaling maandag nog niet is ontvangen, verstuur de bestelling dan niet.',requirements:['Conditional no-shipping if payment absent by Monday.']});
add('n7','memory_trap','Please do not repeat that.','The listener should not repeat the previous statement. This is a negated request.',{action:'translate',memory:'NONE',reference:'Herhaal dat alstublieft niet.',requirements:['Do not choose the positive repeat phrase from memory.']},{memory});
add('n8','memory_trap','I do not have a reservation.','The person has no reservation. Preserve the negation.',{action:'translate',memory:'NONE',reference:'Ik heb geen reservering.',requirements:['Do not choose the positive reservation phrase from memory.']},{memory});
add('a1','clarification','Meet me at the bank.','No further context is available. It is unknown whether bank means a financial institution or a riverbank.',{action:'clarify',requirements:['Ask which meaning of bank; do not choose arbitrarily.']},{senseOptions:{financial:'financial institution; bank',river:'riverbank; oever'}});
add('a2','clarification','Please move it there.','There is no preceding conversation, no visible object, and no indicated destination. The listener cannot identify either it or there.',{action:'clarify',requirements:['Ask for the object and destination rather than inventing them.']});
add('a3','clarification','Set the amount to fifteen—no, fifty—','The transcript ends immediately after the correction; the speaker was interrupted and has not confirmed the final amount.',{action:'clarify',requirements:['Ask the final intended amount. Do not guess 15 or 50.']});
add('a4','clarification','Send the file to him, not him.','Two different men were being pointed at, but the visual gestures and identities are unavailable.',{action:'clarify',requirements:['Ask which recipient; the text alone does not distinguish the men.']});
const json=JSON.stringify(cases,null,2)+'\n';await writeFile('cases.json',json);await writeFile('frozen-protocol.json',JSON.stringify({frozenAt:new Date().toISOString(),casesSha256:createHash('sha256').update(json).digest('hex'),n:cases.length,categories:Object.fromEntries([...new Set(cases.map(c=>c.category))].map(k=>[k,cases.filter(c=>c.category===k).length])),model:'Qwen/Qwen3-30B-A3B-Instruct-2507',temperature:0,jev:'jev-latest',cacheThreshold:.9,clarifyThreshold:.8,translateThresholdForCache:.75,design:'paired, deterministic shuffled case order; alternating within-pair baseline/assisted order; identical material in both arms',outcome:'correct action AND meaning/context preservation; naturalness reported separately',assisted:'Jev memory/sense/register/action labels; high-confidence memory and clarification may bypass Qwen',fallback:'invalid Jev response is logged and Qwen runs with no advice; failure latency remains included',latency:'end-to-end per arm, all API stages included; excludes audio and playback; one warmup per arm excluded',review:'two blinded AI raters; disagreement reported and adjudicated; not native human certification'},null,2)+'\n');console.log('Frozen cases:',cases.length);
