import{readFile,writeFile}from'node:fs/promises';
const cases=JSON.parse(await readFile('cases.json','utf8'));const rows=JSON.parse(await readFile('results.json','utf8'));if(rows.length!==cases.length*2)throw Error('Run is not complete');
const costs={qwenInputPerToken:1e-7,qwenOutputPerToken:3e-7,jevInputPerToken:4.2e-8};
const cost=r=>(r.usage?.prompt_tokens||0)*costs.qwenInputPerToken+(r.usage?.completion_tokens||0)*costs.qwenOutputPerToken+(r.jev?.usage?.input_tokens||0)*costs.jevInputPerToken;
const mean=a=>a.reduce((s,x)=>s+x,0)/a.length;const median=a=>{a=[...a].sort((x,y)=>x-y);return a.length%2?a[(a.length-1)/2]:(a[a.length/2-1]+a[a.length/2])/2;};
const summaries={};for(const arm of ['baseline','assisted']){const rr=rows.filter(r=>r.arm===arm);summaries[arm]={n:rr.length,meanMs:mean(rr.map(r=>r.totalMs)),medianMs:median(rr.map(r=>r.totalMs)),minMs:Math.min(...rr.map(r=>r.totalMs)),maxMs:Math.max(...rr.map(r=>r.totalMs)),estimatedUsd:rr.reduce((s,r)=>s+cost(r),0),qwenInputTokens:rr.reduce((s,r)=>s+(r.usage?.prompt_tokens||0),0),qwenOutputTokens:rr.reduce((s,r)=>s+(r.usage?.completion_tokens||0),0),jevInputTokens:rr.reduce((s,r)=>s+(r.jev?.usage?.input_tokens||0),0),llmCalls:rr.reduce((s,r)=>s+(r.llmCalls||0),0),jevCalls:rr.reduce((s,r)=>s+(r.jevCalls||0),0),routes:Object.fromEntries([...new Set(rr.map(r=>r.route))].map(route=>[route,rr.filter(r=>r.route===route).length]))};}
const pairs=cases.map(c=>{const b=rows.find(r=>r.id===c.id&&r.arm==='baseline');const a=rows.find(r=>r.id===c.id&&r.arm==='assisted');return {id:c.id,category:c.category,baselineMs:b.totalMs,assistedMs:a.totalMs,deltaMs:a.totalMs-b.totalMs,baselineUsd:cost(b),assistedUsd:cost(a),deltaUsd:cost(a)-cost(b),baselineAction:b.output?.action,assistedAction:a.output?.action,expectedAction:c.gold.action,baselineActionCorrect:b.output?.action===c.gold.action,assistedActionCorrect:a.output?.action===c.gold.action,route:a.route,memoryId:a.memoryId||null};});
let seed=1932;const rand=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};const boots=[];for(let b=0;b<10000;b++){let total=0;for(let i=0;i<pairs.length;i++)total+=pairs[Math.floor(rand()*pairs.length)].deltaMs;boots.push(total/pairs.length);}boots.sort((a,b)=>a-b);
const categories={};for(const category of [...new Set(cases.map(c=>c.category))]){const pp=pairs.filter(p=>p.category===category);categories[category]={n:pp.length,baselineMeanMs:mean(pp.map(p=>p.baselineMs)),assistedMeanMs:mean(pp.map(p=>p.assistedMs)),meanDeltaMs:mean(pp.map(p=>p.deltaMs)),baselineMedianMs:median(pp.map(p=>p.baselineMs)),assistedMedianMs:median(pp.map(p=>p.assistedMs)),baselineActionCorrect:pp.filter(p=>p.baselineActionCorrect).length,assistedActionCorrect:pp.filter(p=>p.assistedActionCorrect).length};}
const summary={costs,costNote:'Estimated from observed token usage; Qwen rates from saved provider metadata, Jev $0.042/MTok per TypeSafe models documentation. Not an invoice.',summaries,paired:{meanDeltaMs:mean(pairs.map(p=>p.deltaMs)),medianDeltaMs:median(pairs.map(p=>p.deltaMs)),bootstrapMeanDelta95CI:[boots[250],boots[9750]],pairedBootstrapCaveat:'Describes this fixed selected case set, not a random sample of real conversations.'},categories};
await writeFile('performance-summary.json',JSON.stringify(summary,null,2)+'\n');await writeFile('paired-results.json',JSON.stringify(pairs,null,2)+'\n');
let counter=0;const mapping={};const blind=cases.map((c,i)=>{const rr=rows.filter(r=>r.id===c.id);if(i%2===0)rr.reverse();return {id:c.id,source:c.material.source,context:c.material.context,gold:c.gold,outputs:rr.map(r=>{const code='o'+String(++counter).padStart(3,'0');mapping[code]={id:r.id,arm:r.arm};return{code,action:r.output?.action,text:r.output?.text};})};});await writeFile('blind-review-input.json',JSON.stringify(blind,null,2)+'\n');await writeFile('review-mapping.json',JSON.stringify(mapping,null,2)+'\n');console.log(JSON.stringify(summary,null,2));
