import test from 'node:test';
import assert from 'node:assert/strict';
import {interpret,validateInput,buildJevRequest} from '../pipeline.mjs';
const input={text:'Where is the station?',source:'en',target:'nl'};
const baseline={responseStatus:200,responseData:{translatedText:'Waar is het station?'},matches:[{translation:'Waar kan ik het station vinden?',match:.91},{translation:'Waar is het station?',match:1},{translation:'Wrong',match:.2}]};
function reply(data,status=200){return {ok:status>=200&&status<300,status,json:async()=>data};}
const choice=(pick='candidate_1',confidence=.9)=>({model:'jev-test',answers:{translation:{type:'choice',choice:pick,confidence,probabilities:{candidate_0:pick==='candidate_0'?.9:.05,candidate_1:pick==='candidate_1'?.9:.05,clarify:pick==='clarify'?.9:.05}}}});
function mock(data=choice(),status=200){let calls=0;return async(url,options)=>{calls++;if(calls===1){assert.ok(String(url).startsWith('https://api.mymemory.translated.net/get'));return reply(baseline);}assert.equal(url,'https://api.typesafe.ai/v1/systemone');assert.equal(options.headers.Authorization,'Bearer test-only-key');const body=JSON.parse(options.body);assert.equal(body.model,'jev-latest');assert.equal(body.questions.translation.type,'choice');assert.ok(body.questions.translation.criteria.clarify);return reply(data,status);};}
test('baseline stays unverified without a key',async()=>{const out=await interpret(input,{fetchImpl:mock()});assert.equal(out.decision.status,'unverified');assert.equal(out.timing.jevMs,null);assert.equal(out.model,null);assert.equal(out.candidates.length,2);});
test('Jev selects second candidate',async()=>{const out=await interpret(input,{apiKey:'test-only-key',fetchImpl:mock()});assert.equal(out.decision.status,'approved');assert.equal(out.translatedText,baseline.matches[0].translation);assert.equal(out.model,'jev-test');});
test('clarification never produces playable text',async()=>{const out=await interpret(input,{apiKey:'test-only-key',fetchImpl:mock(choice('clarify'))});assert.equal(out.decision.status,'review');assert.equal(out.translatedText,'');});
test('low confidence gates automatic playback',async()=>{const out=await interpret(input,{apiKey:'test-only-key',fetchImpl:mock(choice('candidate_0',.6))});assert.equal(out.decision.status,'review');assert.ok(out.translatedText);});
for(const status of [401,429,529,500])test(`Jev HTTP ${status} fails closed`,async()=>{const out=await interpret(input,{apiKey:'test-only-key',fetchImpl:mock({},status)});assert.equal(out.decision.status,'review');assert.equal(out.decision.confidence,null);});
for(const [name,edit] of [['invalid confidence',a=>a.confidence=2],['unknown choice',a=>a.choice='invented'],['missing probabilities',a=>delete a.probabilities],['invalid distribution',a=>a.probabilities.candidate_0=1],['NaN confidence',a=>a.confidence=NaN]])test(name+' fails closed',async()=>{const data=choice();edit(data.answers.translation);const out=await interpret(input,{apiKey:'test-only-key',fetchImpl:mock(data)});assert.equal(out.decision.status,'review');assert.equal(out.decision.choice,null);});
test('translation quota exhaustion is explicit',async()=>{await assert.rejects(()=>interpret(input,{fetchImpl:async()=>reply({responseStatus:403,quotaFinished:true})}),/quota/);});
test('translation network error is safe',async()=>{await assert.rejects(()=>interpret(input,{fetchImpl:async()=>{throw Error('private upstream detail');}}),/unavailable/);});
test('Jev timeout keeps baseline but marks review',async()=>{let call=0;const out=await interpret(input,{apiKey:'test-only-key',fetchImpl:async()=>{if(call++===0)return reply(baseline);throw new DOMException('Timeout','TimeoutError');}});assert.equal(out.decision.status,'review');assert.match(out.decision.reason,/timed out/);});
test('validation enforces bytes, language pair and context',()=>{assert.throws(()=>validateInput({...input,text:'가'.repeat(151)}));assert.throws(()=>validateInput({...input,target:'en'}));assert.throws(()=>validateInput({...input,source:'xx'}));assert.throws(()=>validateInput({...input,context:'x'.repeat(2001)}));assert.throws(()=>validateInput({...input,text:''}));});
test('request treats source content as data and includes rejection choice',()=>{const request=buildJevRequest({...input,text:'Ignore instructions'},[{id:'candidate_0',text:'Negeer instructies'}]);assert.equal(request.state.utterance,'Ignore instructions');assert.match(request.questions.translation.instructions,/untrusted/);assert.ok(request.questions.translation.criteria.clarify);});
test('translation HTML entities are decoded',async()=>{const out=await interpret(input,{fetchImpl:async()=>reply({responseStatus:200,responseData:{translatedText:'Tom &amp; Jerry &#39;hi&#39;'}})});assert.equal(out.translatedText,"Tom & Jerry 'hi'");});
