import {readFileSync} from 'node:fs';
import {validateTurn,buildJevRequest,parseDecisions,resolveRoute,JEV_MODEL} from './decision-gate.mjs';
import {createProviders,createBudget} from './providers.mjs';
const defaultMemory=JSON.parse(readFileSync(new URL('./memory.json',import.meta.url),'utf8'));
export function createInterpreter({jevKey='',qwenKey='',model=JEV_MODEL,fetchImpl=fetch,memory=defaultMemory,providers,maxCalls=60,timeoutMs=12000}={}) {
  if(!Array.isArray(memory)||memory.length>32||new Set(memory.map(m=>m?.id)).size!==memory.length||memory.some(m=>!m||!(/^[a-z][a-z0-9_]{0,31}$/).test(m.id)||['constructor','prototype','__proto__'].includes(m.id)||typeof m.english!=='string'||typeof m.dutch!=='string'||!m.english||!m.dutch||m.english.length>1000||m.dutch.length>1000))throw new Error('Memory must contain up to 32 uniquely identified English/Dutch phrases.');
  const phrases=structuredClone(memory);const budget=createBudget(maxCalls);
  const adapter=providers ?? createProviders({jevKey,qwenKey,model,fetchImpl,timeoutMs,budget});
  return {
    get remainingCalls(){return budget.remaining;},
    async interpret(input) {
      const turn=validateTurn(input),started=performance.now();
      const request=buildJevRequest(turn,phrases,model);
      let decisions,actualModel=model,decisionMs=0,translationMs=0;
      const base=()=>({mode:'live',sourceText:turn.text,decisions:decisions??{},model:actualModel,timing:{decisionMs,translationMs,totalMs:Math.round(performance.now()-started)},usedTranslator:false,translatedText:'',clarification:''});
      const decisionStart=performance.now();
      try {const result=await adapter.decide(request);decisions=parseDecisions(result,request.questions);actualModel=typeof result.model==='string'?result.model:model;}
      catch {decisionMs=Math.round(performance.now()-decisionStart);return {...base(),route:'review',reason:'The decision gate is unavailable or returned invalid data. Nothing was translated or approved.'};}
      decisionMs=Math.round(performance.now()-decisionStart);
      const outcome=resolveRoute(decisions,phrases);
      if(outcome.route!=='translate')return {...base(),...outcome};
      const translationStart=performance.now();
      try {
        const translatedText=await adapter.translate(turn,decisions);translationMs=Math.round(performance.now()-translationStart);
        if(typeof translatedText!=='string'||!translatedText.trim()||translatedText.length>8000)throw new Error('Invalid translation.');
        return {...base(),route:'translate',usedTranslator:true,translatedText,reason:'Generated by Qwen using the Jev routing decisions. Review before playback; this is not a certified translation.'};
      } catch(error) {translationMs=Math.round(performance.now()-translationStart);return {...base(),route:'review',usedTranslator:!['not_configured','budget_exhausted'].includes(error?.code),reason:'A new translation is needed, but the translator is unavailable or returned invalid data. Nothing is approved for playback.'};}
    }
  };
}
